### ISSUE TITLE
other game?

### ISSUE THREAD

**Issue by maxman2103** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#2]
this asset unpacker is amzing .thank you for this. i was wondering can i use on other game asset??

**Comment by Nightshades1** [comment]
Hello, glad that u like it ;) obviously it was only meant for this game.

**Comment by salieri-as** [comment]
Hello, i stumbled upon this. few months ago, Bamco added another protection layer into the .bin files.

the image files (.png) and another kind of files type decryption still works as intended.

So could you take a look into the .bin files?
i could provide the files if needed.

i'm here at Discord if you need more details:
Salieri#6041
