### ISSUE TITLE
Image Files with dark shades

### ISSUE THREAD

**Issue by roryAlicer** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#4]
Hello, not sure if u are still there. I noticed that the image files converted have some sort of dark shade behind the image, like dark edge around the characters. I can provide more detail if you still want to dig into it :D please let me know

**Comment by Nightshades1** [comment]
Im not really playing the game anymore but could rewrite a new software if wanted, do you think its an issue or is this normal (is it the .png ?) because i used built-in function to save them as PNG, if this 'shade' is not an issue of alpha channel but part of the texture to act as a shader or w/e it could be a skill effect then its normal.

Would be nice to upload an image to describe the issue, and my unpacker was kinda a hackish solution :D

**Comment by roryAlicer** [comment]
Thanks for replying! This is the preview for it, the right one showing some sort of black edges around the flower. https://imgur.com/iUJwz1T

**Comment by roryAlicer** [comment]
The software is excellent and I kept using it for years, really wish you can fix this minor issue here :D

**Comment by Nightshades1** [comment]
Is the flowers glowing in-game or anything ? That black looks like its being used to act as a 'shader' for instance on ps1 the black color pixel rgb in hex was 0x00, they could then apply transparency that way, so im wondering if they applied a specific color on these flowers.

After it could be a issue with that old outdated unpacker lol, its worth having a look later i guess, is this only on this image the issue or the others are fine ?

**Comment by roryAlicer** [comment]
The flowers are glowing in game, but not sure which way they implemented lol since I'm not particular familiar with that.

**Comment by Nightshades1** [comment]
I should have a look later then :joy:.

**Comment by roryAlicer** [comment]
> I should have a look later then 😂.

Thanks!

**Comment by Nightshades1** [comment]
> 
> 
> > I should have a look later then joy.
> 
> Thanks!

Btw would be easier if we continue the discussion on discord, add me Diablo_IV#0955

**Comment by roryAlicer** [comment]
> Diablo_IV#0955

Request Sent!
