### ISSUE TITLE
Stops Responding

### ISSUE THREAD

**Issue by Kitsunejasutin** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#5]
Good Day NightShades! I'm very happy that you created this app. It is very useful, Thank you! I just want to report that the app becomes unresponsive when creating actual database version. It force stops. Any leads why this is happening? Is there any logs or anything that I can send for more insight to the error? Thank you!

**Comment by Nightshades1** [comment]
Hello, if you could upload your main manifest file (project.manifest) i would look into it

**Comment by Kitsunejasutin** [comment]
Good Day, I usually get the image folder only. I don't have the whole game data. Should I create actual database file with the whole game data? *edit* I manage to adb pull the whole download folder and it works now xD sorry for my dumb report, project.manifest is indeed needed. I think Thank you for reply! Thanks for the app too 😘 I might close this issue now.
