### ISSUE TITLE
Accel World vs. Sword Art Online: Millennium Twilight can't open the .APK files!!! HELP!!! 

### ISSUE THREAD

**Issue by QBASpriteFinder** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#6]
No matter what I seem to do I can't seem to open the .APK files in this game! Is there any to extract the .APK file from this game so that I can get the 2D Sprites!?

**Comment by Nightshades1** [comment]
Hello, this is only for Sword Art Online: Memory Defrag and no other game actually, unless they use the same system which i doubt.
