### ISSUE TITLE
project.manifest

### ISSUE THREAD

**Issue by blubblub-web** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#7]
Greetings. Forgive me infinitely for the inconvenience, but after an exhausting day of research, I could not find anything about the “project.manifest” file that goes inside the software download folder. It says that it is possible to get it from the game through emulators,
Could you please be a little more specific? That I don't really know where to put my hands.

**Comment by longxa762** [comment]
Extract the game apk using 7zip, project.manifest should be inside "apkfoldername \assets \ tc-en-kr (languages)".

You better hurry though as the game has shut down, you can still download all assets using this program but no one knows how long Bandai servers is going to stay up.

Also use the apk of version 2.6.1 and below as 3.0.0 has changed everything to be locally.

**Comment by blubblub-web** [comment]
Got it. Thank you so much!
In fact, I am using the version just before the last release.

**Comment by Nightshades1** [comment]
> Got it. Thank you so much!
> In fact, I am using the version just before the last release.

Hey, glad that you got it working, it is very easy to use, and yeah i have never touched the software since i released it nor played the game anymore ^^
