### ISSUE TITLE
Question on list of old assets being saved

### ISSUE THREAD

**Issue by willypt** [Nightshades1/Sword-Art-Online-MD---Asset-Unpacker#8]
Hi @Nightshades1, currently some of our members in SAO: MD Revival Project is scouring the internet to collect old assets from the previous versions of the game.

Do you by chance kept assets of SAO: MD before 3.0.0? Perhaps 2.6.1 or 2.1.4 would be amazing.

**Comment by Nightshades1** [comment]
Unfortunately i didn't as i had never reinstalled the game at all and i reformated my pc to transition from win7 to 10+, ultimately you could always ask the developer since its the end of life i doubt that they even bother, knowing that it may be to make a server emulator project just behind, as this game was kinda pretty easy networking wise, if they took down their CDN its gonna be hard to get them lol.

**Comment by Nightshades1** [comment]
@willypt Hello, I unarchived the repo, You are lucky on my PC, i had obviously tested it, I kept all the assets intact in the form of .zip, i thought i had deleted all of them but i didn't Lol. (exactly like on their CDN, this was the last full CDN download from 1.42.93) You could still use the software to decrypt all assets if needed.
![image](https://user-images.githubusercontent.com/19496833/155566216-2db4536b-52fd-4697-8c66-a855c20635e4.png)

Also i seen on the web that they had released an offline version just before they took down the game ? Isn't your best bet to go on apk mirror and download this instead ? Or did they get rid of all the packet handlers, would be a problem if there's no API request to make a server emulator lol.

It contains 744 .zip of assets, with everything as of Version 1.42.93.

**Comment by Nightshades1** [comment]
![image](https://user-images.githubusercontent.com/19496833/155566860-b5648346-cdb6-43ef-8717-ce24d69bf609.png)
Just a .png search in the "Story" folder.

**Comment by Nightshades1** [comment]
I will release it and update the readme.md, i don't have anything else that could help, hopefully it help you guys on your project.

**Comment by willypt** [comment]
Thank you and Amazing JOB!!!!!
Surely this will help a lot!
